### PR TITLE
Chatcolors to Turquoise

### PR DESCRIPTION
**Pull request by voshond**
Mediumpurple turned out to be bad on some Backgrounds + Found some old
Blue Brushes to change.

### CODE REVIEW

**Comment by secretdataz** [comment]
Can you provide a screenshot so we can compare between current and this?

**Comment by voshond** [comment]
capture4

here you can see both in comparison

**Comment by NitroXenon** [comment]
:+1:

**Comment by secretdataz** [comment]
Looks good

**Pull request merged**
