### PR TITLE
 Haven't made a pull in a while

### PR DESCRIPTION
**Pull request by Dispersia**

### CODE REVIEW

**Comment by horato** [comment]
glhf merging that lol

**Comment by eddy5641** [comment]
Doing it right now :P Also Hi Desp

**Comment by eddy5641** [comment]
and git hates me and will not let me merge -.- (Says that they are the same but they aren't)

**Comment by Dispersia** [comment]
wait what, I fixed all merge conflicts before I did a pull, wtf lol? I can't fix those apparently >.< sorry

**Comment by eddy5641** [comment]
It is okay :P (Variable not being renamed like crazy anymore [what happened to _var_... oh it is __var_ now])

**Comment by Dispersia** [comment]
ya, I saw -that- guy was gone, so meh might as well work on it again, fun project

**Comment by eddy5641** [comment]
Ya RoachxD sortof died. I made you a colab again. Welcome back :)
(btw I removed Roach for now because not many changes now)

**Comment by Dispersia** [comment]
Cool. I'm learning web development, so I should be able to make a 'decent' website soon. Idk if you have a host or not though, if not it would just simply be on my site unless you don't care :P (I also was planning to add things such as live match data [obviously three minute delay] and other features you could access directly from the website, such as streamers being able to open an invite panel to invite people, etc)

**Comment by eddy5641** [comment]
K yay :+1:

**Pull request merged**
