### PR TITLE
Added nuget packages and fixed CI build failed

### PR DESCRIPTION
**Pull request by NitroXenon**

### CODE REVIEW

**Comment by secretdataz** [comment]
These change aren't needed. You just have to add "nuget restore" in before build script.
And nuget will do the job perfectly.

Please see https://ci.appveyor.com/project/secretdataz/legendaryclient/build/1.0.3

**Comment by NitroXenon** [comment]
but I think this change is better for new contributer od LC. They dont need to download those packages again.

When I start working on this project, there are some packages missing and I mees to add them back manually.

So, who care about it?

**Comment by secretdataz** [comment]
Isn't it an automated process?

**Comment by NitroXenon** [comment]
No, my VS 2013 will pop up an error

**Comment by secretdataz** [comment]
Weird, I just click build and it does the job for me.

**Pull request merged**
