### PR TITLE
Updating MainWindow.xaml

### PR DESCRIPTION
**Pull request by naeem76**
using MahApps Drop Shadow property on MainWindow, looks much better

### CODE REVIEW

**Comment by NitroXenon** [comment]
WTF!? You use "//" to make comment in a xaml file...

**Comment by newchild** [comment]
I don't see the problem Nitro :S
It seems it is only at the wrong place

**Comment by NitroXenon** [comment]
Ok so what should we do now? Merge it?

**Comment by NitroXenon** [comment]
It should be a syntaz error. In xaml, we can't make comment using "//" because in xaml namespace we have "http://".

So we should use  to comment out sth.

See [this](http://stackoverflow.com/questions/7921672/how-to-add-comments-into-a-xaml-file-in-wpf)

**Comment by NitroXenon** [comment]
Also, there are two closing...

```
<Controls:MetroWindow x:Class="LegendaryClient.MainWindow" xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
                      xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
                      xmlns:Controls="clr-namespace:MahApps.Metro.Controls;assembly=MahApps.Metro"
                      x:Name="LegendaryWindow"
                      Title="LegendaryClient" Width="1200" Height="850" MinWidth="900" MinHeight="650"
                      SaveWindowPosition="True" TitleCaps="False"
                      WindowStartupLocation="CenterScreen"
                      TitleForeground="Transparent"
                      Closing="MainWindow_Closing">
﻿                     
﻿                     //DropShadow MainWindow
﻿                     EnableDWMDropShadow="True"
                      ResizeMode="CanResizeWithGrip"
                      WindowTransitionsEnabled="False">
```

**Comment by nairaner** [comment]
OK, i added it manually, but why did @naeem76 add

```
WindowTransitionsEnabled="False"
```

**Comment by NitroXenon** [comment]
No idea... Close this pr first

**Pull request closed without merging**
