### PR TITLE
new MainPage and ChampSelect

### PR DESCRIPTION
**Pull request by voshond**
MainPage
mainpage
ChampSelect
champselect

### CODE REVIEW

**Comment by NitroXenon** [comment]
Wow amazing and aero feel.

I think that the dodge button move to the bottom left/right corner is better :/

**Comment by voshond** [comment]
yeah i was thinking about that.
all WIP tho.
the Picks and Bans are about to be updated so i didnt know how much space we have left there.
and its hard to test in Draftpick since i cant seem to create one where bots banning.

Feedback if appreciated ofc!
i also wanted to make the Dodgebutton as a 5px bar with maximum pagewidth but then i felt without a Label or Icon inside it might be not self explaining

**Comment by voshond** [comment]
Something like this
dodgebar

**Comment by voshond** [comment]
or this
dodgebar2

**Comment by RoachxD** [comment]
Bitches, I will make my version, won't update it, maybe making another branch xD

**Pull request merged**
