### PR TITLE
disable spectator PH and TW on MainPage

### PR DESCRIPTION
**Pull request by nongnoobjung**
disable spectator PH and TW on MainPage
Because haven't featured url and spectator ip

### CODE REVIEW

**Comment by NitroXenon** [comment]
TW have spectator server :/

**Comment by nongnoobjung** [comment]
no IP in LC :/

**Comment by secretdataz** [comment]
Only adding check if there's no spectating IP is enough IMO.

**Comment by NitroXenon** [comment]
yes. so close this pull request

**Pull request closed without merging**
